name: med_assist
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  freezed: ^2.4.6
  #HTTP request package
  dio: ^5.4.0

  
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  loading_indicator: ^3.1.1
  otp_text_field: ^1.1.3
  intl: ^0.19.0
  country_picker: ^2.0.25
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  http: ^1.2.1
  firebase_messaging: ^14.9.1
  firebase_core: ^2.30.1
  awesome_notifications: ^0.9.3+1
  pull_to_refresh: ^2.0.0
  pull_to_refresh_flutter3: ^2.0.2
  file_picker: ^8.0.3
  path: ^1.9.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true
  assets:
    - assets/icons/